### ISSUE TITLE
Any ability to use web camera STILL image mode to take picture?

### ISSUE THREAD

**Issue by jdredd87** [FactoryXCode/MfPack#11]
I want to take a still image.  Not just save a random frame from a video stream.

Using the Windows Media Foundation API ( not DirectX )

If you use Windows 10 Camera app, say on a surface pro.
The preview mode is 1920x1080 mode.
But when you take the STILL image, it is 3264x2448 ( 8 MP )

Downloaded latest MF pack and don't see this ability. So not sure if it is there and missing something.
If it does, can a demo be added?

**Comment by FactoryXCode** [comment]
Hello, 

Depending on the hardware a still image, snap-shot or freeze-frame kan be taken from it's still image pin. For this you have to use DirectShow. [Capturing an Image From a Still Image Pin](https://docs.microsoft.com/en-us/windows/win32/directshow/capturing-an-image-from-a-still-image-pin)

Media Foundation does not (yet) have this ability. However in combination with the WIC (which is also part of MfPack), it is possible to pick a frame from the videostream and convert this frame to the proper format. [as been suggested here](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/7d2686cc-bba4-445b-a9af-2bc9ca804cb1/how-to-use-media-foundation-to-capture-a-webcam-shot-still-to-image-file?forum=mediafoundationdevelopment)

A good readable "how to" can be found [here on Code Project](https://www.codeproject.com/Articles/776058/Capturing-Live-video-from-Web-camera-on-Windows-an) 

For now, we are not working on a sample that's not based on MF and D3D9, but who knows.. ;-) 

Greetings, Tony.
