### ISSUE TITLE
Wrong translation of PCWSTR

### ISSUE THREAD

**Issue by pyscripter** [FactoryXCode/MfPack#2]
In MfPack.MfpTypes.pas PCWSTR is defined as

```
{$IFDEF MFP_LPCWSTR}
  PCWSTR = WideChar;
  {$EXTERNALSYM PCWSTR}
  LPCWSTR = PWideChar;
  {$EXTERNALSYM LPCWSTR}
{$ENDIF}
```

This is wrong PCWSTR is defined in https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types

> PCWSTR | A pointer to a constant null-terminated string of 16-bit Unicode characters. For more information, see Character Sets Used By Fonts.This type is declared in WinNT.h as follows:
> 
> `typedef CONST WCHAR *PCWSTR;
> `
> 

I think the correct translation is 

`PCWSTR = PWidechar
`

The difference from LPWSTR is that it implies that it cannot be modified by the called function.
See also https://stackoverflow.com/questions/21659751/pcwstr-vs-lpwstr

**Comment by FactoryXCode** [comment]
I have to check that.  A long pointer (LP) in C implifies a pointertype in Delphi. However  a pointer type will be called by reference by the compiler. Microsoft referencenses to a WCHAR for this type (WChar = PCWSTR) .  So, PCWSTR = WideChar should be correct. Correct me if I'm wrong ;-)

**Comment by pyscripter** [comment]
Just read the links.
Also look at https://github.com/CMCHTPC/DelphiDX12

**Comment by FactoryXCode** [comment]
Thanks!
I think this is a better explanation. [Working with strings](https://docs.microsoft.com/en-us/windows/win32/learnwin32/working-with-strings) Note: CMCHTPC (translations for FPC) has to many flaws and is incomplete to rely on. I committed the changes.
