### ISSUE TITLE
Order of overloaded functions.

### ISSUE THREAD

**Issue by pyscripter** [FactoryXCode/MfPack#4]
Have a look at the [discussion](https://en.delphipraxis.net/topic/3233-translation-of-c-headers/)  about ID2D1SvgElement, but the points made are more general.

**Comment by FactoryXCode** [comment]
This is a known issue. Before Delphi introduced the overload directive, we used an underscore as prefix or suffix for a c method or its elements with a name that clashes. Should test IT.

**Comment by FactoryXCode** [comment]
Ok, I investigated this interface.

In 20 years translating MS interfaces, I never trapped a wrong interface implementation sequence of methods by MS in their headers. Wrong documentation is another aspect. But always better than the Google API's. ;-)
 I don't know who wrote the D1D2 API here, All I know it was a hasty thing to make an example working, and Embarcadero did not update their thing.

<deleted the codesection>

So, before making your conclusions public, I suggest to adjust and check your version of Interface ID2D1SvgElement.

**Comment by pyscripter** [comment]
Have you looked at https://en.delphipraxis.net/topic/3233-translation-of-c-headers
The correct order of overloads is shown in the image below and is different than the order in the c header.   I was quite surprised by that.   Please read the explanations of Mahdi Safsafi.
![image](https://user-images.githubusercontent.com/1311616/89599419-34aa5d00-d868-11ea-9729-08745ef784a8.png)

Every single overload has been tested and I can confirm the correctness of this order.

**Comment by FactoryXCode** [comment]
I was surprised too.
However, It leaves the following issue:
The occurence of for example "function SetAttributeValue" in your sourcecode is 3 times.
When I check the API it should be 14. 

Those are the overloaded functions I found, and to keep things simple, I just implemented the SetAttribute functions: 

`ID2D1SvgElement = interface(ID2D1Resource)
   ['{ac7b67a6-183e-49c1-a823-0ebe40b0db29}']

function SetAttributeValue({_In_} name: PCWSTR;
                            _type: D2D1_SVG_ATTRIBUTE_POD_TYPE;
                            value: Pointer;
                            valueSizeInBytes: UINT32): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           {_In_} value: ID2D1SvgAttribute): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: FLOAT): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: D2D1_COLOR_F): HResult; overload; stdcall;

function SetAttributeValue({_In_}name: PCWSTR;
                           value: D2D1_FILL_MODE): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: D2D1_SVG_DISPLAY): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: D2D1_SVG_LINE_JOIN): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: D2D1_SVG_LINE_CAP): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: D2D1_SVG_VISIBILITY): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: D2D1_MATRIX_3X2_F): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: D2D1_SVG_UNIT_TYPE): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: D2D1_EXTEND_MODE): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: D2D1_SVG_PRESERVE_ASPECT_RATIO): HResult; overload; stdcall;

function SetAttributeValue({_In_} name: PCWSTR;
                           value: D2D1_SVG_LENGTH): HResult; overload; stdcall;
end;
IID_ID2D1SvgElement = ID2D1SvgElement;
`

However, for example,  when you compile this, you will get 6 exceptions: E2252 Method 'SetAttributeValue' with identical parameters already exists.

There are 2 posible things I can think of: The guy who translated this API dropped a bunch of functions to get rid of the exceptions. Or Delphi it selves has a bug.

**Comment by pyscripter** [comment]
> The occurence of for example "function SetAttributeValue" in your sourcecode is 3 times.
> When I check the API it should be 14.

The remaining ones are implemented as inline C functions.  They are not part of the Interface VTable.   You can do all that using the functions of the interface.

**Comment by FactoryXCode** [comment]
As I see, thank you.
I dropped a question about this interface on msdn.
Maybe someone knows about this strange thing.

**Comment by FactoryXCode** [comment]
Took some while to find my old decompiler, but it looks like the API in the headerfile  is wrong and it's not a Delphi thing.

![image](https://user-images.githubusercontent.com/41634066/89695834-bc01da00-d915-11ea-89f4-6913d674cbbe.png)
![image](https://user-images.githubusercontent.com/41634066/89695847-c9b75f80-d915-11ea-8b7a-bb7c1b3e7368.png)

Still leaves one point: 

 `function GetAttributeValue(name: PCWSTR;
                               _type: D2D1_SVG_ATTRIBUTE_POD_TYPE;
                               value: Pointer;
                               valueSizeInBytes: UINT32): HResult; overload; stdcall;`
should be the first one in the sequence?

**Comment by FactoryXCode** [comment]
Ok, I checked: It's not a Delphi thing (What a joy), but a wrong declaration in the header file.
Took some time to find my disassembler, but here the results:
![image](https://user-images.githubusercontent.com/41634066/89696492-6418a280-d918-11ea-8e02-c0b50224944f.png)
![image](https://user-images.githubusercontent.com/41634066/89696500-6c70dd80-d918-11ea-973c-ffcc89cbdd96.png)

**Comment by FactoryXCode** [comment]
We reopened this issue, because Microsoft is running an investigation on this issue.

**Comment by FactoryXCode** [comment]
Well we are comming to something.
First of all: The original declaration of ID2D1SvgElement is probably correct! 
Changing the method order results in multiple errors using the original  Microsoft D2DSvgImage sample ( with some changes concerning the use of inline functions). 
The problem probably hints to a wrong D2D1 initialization sequence. 
For instance: SetAttributeValue should be called before GetAttributeValue. 
If nothing is set there is nothing to get! And result is a Nil and hresult is 'The parameter is incorrect.'
We did an experiment to alter the header as suggested and run it in VS2019. Well, that wents out to be a disaster: The MS sample did not work anymore.
Most likely the thing is: The Delphi (sample ?)  [svg code]( https://en.delphipraxis.net/topic/3233-translation-of-c-headers) is bogus or as Kas oB mentioned: there is an ussue with Delphi.
We are investigation this issues further on, but until now it points to a wrong usage of D2D1.

**Comment by pyscripter** [comment]
There is nothing wrong with the C-Header and you should not change it.   The correct Delphi translation of the C header is at question.  The Delphi declaration order should match the order you see with IDA (your post above).

**Comment by FactoryXCode** [comment]
The translation of the header is correct, as well as the sequence of the official interface declaration.
Yes, you are right about the vtable, however we need the vtable from memory, not the static one. 
That's why I deleted that post, because it gives a false interpretation of vtables.
In early days I used SoftICE for that, now Syser seems to be good. I'll give a try on that if nothing else helps.
I dropped the question by IDERA, maybe there is someone with a solution for this strange behavior.

**Comment by FactoryXCode** [comment]
Ok, as I understand now, the original c++ header is correct?
We think there is nothing wrong with the translation.
The C++ example discussed [here](https://docs.microsoft.com/en-us/answers/questions/61930/wrong-method-sequence-in-id2d1svgelement-api.html) proves the headerfile is correct.

Now that leaves 2 possibilities:

1 - The Delphi svg sample is not correct, in a way D2D1 / svg is not initialised and/or used the way it should.
2 - Delphi has an issue with overloading methods in C++ interfaces.

So for now, we'll leave the corrected header translation for what it is, until we have a clue from a question asked [here](https://community.idera.com/developer-tools/programming-languages/f/delphi-language/73143/does-delphi-has-an-issue-with-overloaded-functions-with-microsoft-c-interfaces)
by Tony.

Thank you.

**Comment by FactoryXCode** [comment]
> There is nothing wrong with the C-Header and you should not change it. The correct Delphi translation of the C header is at question. The Delphi declaration order should match the order you see with IDA (your post above).

The translation is OK, it's a MS thing: see [#600](https://github.com/microsoft/win32metadata/issues/600)
