### ISSUE TITLE
Thumbnail sample fails

### ISSUE THREAD

**Issue by rmesch** [FactoryXCode/MfPack#55]
Currently the Thumbnail-sample fails, because the boolen pbCanSeek is always returned as false.

Fix: Change the statement around line 612 in Thumbnail.pas to

`hr := m_pReader.GetPresentationAttribute(MF_SOURCE_READER_MEDIASOURCE,//DWord(MF_SOURCE_READER_FIRST_AUDIO_STREAM),
                                           MF_SOURCE_READER_MEDIASOURCE_CHARACTERISTICS,
                                           _var);`

**Comment by rmesch** [comment]
Hi!
I forgot: hr in TForm1.InitializeApp is not initialized. Probably just omit the first succeeded check.

**Comment by FactoryXCode** [comment]
Hi Renate,
Thank you for this.
I'd implement the corrections.
InitializeApp hr used to be initialized by com. However, this has been commented out, but forgot to comment out the next line If succeeded(hr) then ...

Regards, Tony.
