### ISSUE TITLE
Compile failed due to: WinApi.MediaFoundationApi.MfMediaTypeDebug

### ISSUE THREAD

**Issue by drmoorejr** [FactoryXCode/MfPack#56]
Compile failed due to: WinApi.MediaFoundationApi.MfMediaTypeDebug...  because GetGUIDNameConst expected different types...

I made the the followin

from:

```
  pwcGuidName: string;
  pwcFormatTag: string;
  pwcFOURCC: DWord;
  pwcFmtDesc: string;

  pwcValGuidName: string;
  pwcValFormatTag: string;
  pwcValFOURCC: DWord;
  pwcValFmtDesc: string;
```

to:

```
  pwcGuidName: LPWSTR; //string;
  pwcFormatTag: LPWSTR; //string;
  pwcFOURCC: DWord;
  pwcFmtDesc: LPWSTR; //string;

  pwcValGuidName: LPWSTR; //string;
  pwcValFormatTag: LPWSTR; //string;
  pwcValFOURCC: DWord;
  pwcValFmtDesc: LPWSTR; //string;
```

and everything compiled...  let me know if this is correct..

**Comment by FactoryXCode** [comment]
This issue has been corrected with the leatest update #5.
Just download the latest version of this unit [here](https://github.com/FactoryXCode/MfPack/blob/Master/MfPack/src/WinApi.MediaFoundationApi.MfMediaTypeDebug.pas)

Regards, Tony.
