### ISSUE TITLE
MfPackX315.dpk cannot be compiled

### ISSUE THREAD

**Issue by YuzuruJewell** [FactoryXCode/MfPack#63]
Thank you for the great libraray of Delphi.

I could not find WinApi.StiErr.pas written in '..\src\WinApi.StiErr.pas' on line 220 of MfPackX315.dpk.
Maybe it's /debug/WinApi.Dbg.StiErr.pas.
I was able to comment it out and compile MfPackX315.dpk.
I can't determine the need for that file.

Please check it.

**Comment by FactoryXCode** [comment]
Thank for reporting this issue.
The missing file (WinApi.StiErr.pas) has been added to ../src/
Note that "/debug/WinApi.Dbg.StiErr.pas" is a helper for debugging issues.
