### ISSUE TITLE
MfPack\Samples\MfComponents\MfComponents.dpk can't be compiled.

### ISSUE THREAD

**Issue by YuzuruJewell** [FactoryXCode/MfPack#64]
Thank you for the great components of Delphi.

MfComponents.dpk of 3.1.5 can't be compiled.
The 33rd line of MfComponents.dpk had "MfPackX313;" written in it, so I changed it to "MfPackX315;" and was able to install it.
Please fix it.

**Comment by FactoryXCode** [comment]
Thank you for reporting this.
This issue is fixed.
