### ISSUE TITLE
crash with MfCaptureVideoCaptureEngine sample

### ISSUE THREAD

**Issue by BanaIskander** [FactoryXCode/MfPack#67]
Hi,

Thank you for MfPack.

I try to explain my problem:

I run MfCaptureVideoCaptureEngine sample, 
TMainWindow opens
Capture menu > Choose Device > then a crash

I trace the program to the problem:

TMainWindow.CreateDeviceExplorer() >
if Assigned(FDeviceExplorer) then FreeAndNil(FDeviceExplorer); > 
TDeviceExplorer.Destroy(); > 
TDeviceExplorer.ResetCaptureDeviceCaps(); > 
for i := 0 to Length(FDeviceProperties) -1 do FDeviceProperties[i].Reset; > 
TDeviceProperties.Reset(); > 
CoTaskMemFree(aVideoFormats); > crash

aVideoFormats (Ctrl F7 just before crash) : 
((0, nil, (0, 0, 0, (0, 0, 0, 0, 0, 0, 0, 0)), '', (0, 0, 0, (0, 0, 0, 0, 0, 0, 0, 0)), '', 0, '', '', '', ... (very long ...)

with Embarcadero® Delphi 11 Version 28.0.48361.3236 community edition

kindly

**Comment by FactoryXCode** [comment]
Hi, thank you for this.
The issue lays in the fact the dynamic arrays are not properly freed from memory.
In Delphi dynamic arrays are managed types, so they should automatically go out of scope.
But, to be sure you can nil them out.
So, the solution is to replace CoTaskMemFree(dynarray) with dynarray := nil. 
In the mean while I replaced the units involved (DeviceExplorer.pas and WinApi.MediaFoundationApi.MfMetLib) for the  correct ones. 
The issue should be solved.
Regards, Tony.
