### ISSUE TITLE
MFCaptureEngineVideoCapture (crash, unexpected behavior, problem)

### ISSUE THREAD

**Issue by BanaIskander** [FactoryXCode/MfPack#69]
Hello,
allow me to congratulate you on your work before discussing some problems with you (with MFCaptureEngineVideoCapture) 

------------------------------------------------------------------------------------------------

CRASH

if I close the application without doing anything : crash

if I trace the program until it crashes :

unit Utils > 
procedure TChooseDeviceParam.Reset(); >   
for i := 0 to count -1 do 
(problem solved by adding : for i := 0 to Integer(count) -1 do)

-------------------------------------------------------------------------------------------------------

UNEXPECTED BEHAVIOR

when recording starts, « Capture > Start Recording » menu does not change caption

I suggest a change :

unit frmMain.pas >
procedure TMainWindow.UpdateUI(); >
 //*** if not FCaptureManager.IsRecording then begin
  bRecording := FCaptureManager.IsRecording;
  if bRecording then
    mnuStartRecording.Caption := 'Stop Recording'
  else
    mnuStartRecording.Caption := 'Start Recording';
//*** end;

I also modified :

unit frmMain.pas >
procedure TMainWindow.mnuStartRecordingClick(Sender: TObject);
begin
  //*** FCaptureManager.StartRecording(nil);
  if Assigned(FCaptureManager) then
    if FCaptureManager.IsRecording
      then FCaptureManager.StopRecording()
      else FCaptureManager.StartRecording('MfPackTry.mp4');
end;

-----------------------------------------------------------------------------------------------------------

PROBLEM :

when I recorded a first video (successfully) and I try to record again, there is no crash but the new video is empty. I have to redo: Capture menu > Choose Device (eventually I choose the same camera device and the same resolution) so that it records a video correctly.

------------------------------------------------------------------------------------------------------------

Sincerely, Bana

**Comment by FactoryXCode** [comment]
Hi, thank you for reporting this.

The crash is a result that the latest Delphi compiler is more critical.
For i := 0 to x -1 will not work with cardinals like UINT32. So, you can cast it to integer (what you did) or use Low and High.
We are working on these issues at the moment.
Soon a new version will be uploaded, that will be using the IMFMediaEvent to set the proper items.
The last issue you mentioned have to do that the engine needs to be reinitialized.
You can do a work around to prevent the engine freeing essential properties and keep the engine a life.

Regards, Tony.

**Comment by FactoryXCode** [comment]
The new sample has been updated and pushed to GitHub.
