### ISSUE TITLE
MFCaptureEngineVideoCapture

### ISSUE THREAD

**Issue by BanaIskander** [FactoryXCode/MfPack#72]
Hello,

thanks for making a patch very quickly. Unfortunately, the problem remains the same (when I recorded a first video and I try to record again, the new video is empty). 

I noticed the following:

unit CaptureEngine;
FCaptureManager.StartPreview(True); //True is not used by the procedure

Sincerely

**Comment by FactoryXCode** [comment]
Hi,
The issue has been solved. See latest [update.](https://github.com/FactoryXCode/MfPack/tree/Master/MfPack/Samples/MFCaptureEngineVideoCapture)
The reason was the same as with preview, the sinkwriter initializes again, while it should not. 

Regards Tony.
