### ISSUE TITLE
Resolution problem in MFCaptureEngineVideoCapture

### ISSUE THREAD

**Issue by BanaIskander** [FactoryXCode/MfPack#74]
Hello,

Sorry to only write about problems when most of the program works fine.

Whatever the resolution selected (menu Capture > Choose Device) (for example 320x240 with YUY2 video format) the recorded video has always a 640x480 resolution (i.e. the first resolution presented in the list).

Kind regards

**Comment by FactoryXCode** [comment]
Hi, 
Well, it's a sample.
And samples are there to challenge you to find a solution to help understanding the API.  Being that said: The sample is provided with some debug code to help you understanding on what's going on. So my advise is to figure out why you don't get the output you want.

As you could see, the capture engine uses the default videoformat. This has been changed to the given capture and preview formats. See the latest updates. Don't forget to download the latest WinApi.MediaFoundationApi.MfMetLib unit from ../src.

Regards, Tony.
