### ISSUE TITLE
Won't Compile for Delphi 12.2 in 64 bit

### ISSUE THREAD

**Issue by peardox** [FactoryXCode/MfPack#78]
(or 32 bit release actually)

In WinApi.MediaFoundationApi.MfMetLib.pas

1) Line 1268 - The ifdef just above needs moving above the uses

2) Line 2645 - MAXUINT64 is undeclared - add to WinApi.WinApiTypes.pas ???
                       This will also cause problems tho as the function declares stop as LONGLONG - W1012

In WinApi.DirectX.XAudio2.XAudio2Fx.pas

1) - SideDelay is undefined x 3 - I dunno what to do here

**Comment by FactoryXCode** [comment]
Hi, thank you.

MAXUINT64 is for some reason not declared in WinApiTypes.
This has been updated.

SideDelay is is a member of the XAUDIO2FX_REVERB_PARAMETERS record.
However this member is only valid for Windows 10 versions and above. 
The _WIN32_WINNT_WIN10 constant is defined in WinApiTypes.inc by default.
However, if you want to use a windows version < version 10, you should use and alter the MFPACK_WINVER constant. 
By default this constant is assigned with the highest Win version (_WIN32_WINNT_WIN10).
Reason is, that all versions < 10 are not supported by Microsoft anymore.
If you don't want to fiddle with the settings of WinApiTypes.inc and you are shure you only compile for Wins 10 and higher,
you may comment out the compiler directives.

Note:
  - Media Foundation is basicly designed for Windows 10 and above for best performance.
  - There is actually no reason to compile for 64 bit (Media Foundation is based on the Win32 platform).

Regards, Tony.

**Comment by peardox** [comment]
Still a bug in WinApi.MediaFoundationApi.MfMetLib.pas

You have...

```
uses
  {$IFDEF DEBUG}
  WinApi.MediaFoundationApi.MfMediaTypeDebug;
  {$ENDIF}

const
  User32Lib = 'User32.dll';
```

Should be ...

```
  {$IFDEF DEBUG}
uses
  WinApi.MediaFoundationApi.MfMediaTypeDebug;
  {$ENDIF}

const
  User32Lib = 'User32.dll';
```

Otherwise if Build Configuration = Release you'll get a compile error with

> [dcc32 Error] WinApi.MediaFoundationApi.MfMetLib.pas(1268): E2029 Identifier expected but 'CONST' found
> [dcc32 Error] WinApi.MediaFoundationApi.MfMetLib.pas(1269): E2029 Declaration expected but identifier 'User32Lib' found
> [dcc32 Error] WinApi.MediaFoundationApi.MfMetLib.pas(8761): E2003 Undeclared identifier: 'User32Lib'
> [dcc32 Fatal Error] WinApi.CoreAudioApi.AudioProfileUtils.pas(79): F2063 Could not compile used unit 'WinApi.MediaFoundationApi.MfMetLib.pas'
> Failed

**Comment by FactoryXCode** [comment]
Hi
Look at Update #79

Regards Tony.
