### ISSUE TITLE
Unable to play videos in the SimplePlayer sample.  Access Violation reading address 0x00000020

### ISSUE THREAD

**Issue by adaloveless** [FactoryXCode/MfPack#9]
Again, THANKS FOR MAKING THIS...

Note: MFPlayerX works, but SimplePlayer sample does not.  I get an AccessViolation reading address 0x20 on a thread that seems to be deep in the Api.  Screenshot of callstack attached.

![image](https://user-images.githubusercontent.com/40921793/99723090-51654c00-2a77-11eb-8c23-345d65d391c8.png)

note that I got this error trying to play a 1080p mp4 file.  

I also tried playing a Standard Definition MPG file and got audio-only output, no video.

**Comment by FactoryXCode** [comment]
Hi, thank you for letting us know.

I tested this on a Windows 10 machine with the latest updates, to see what's going on.
When rendering different MP4 mediafiles, including 1080p, the issue does not appear.
Depending on the type of MPEG, you can get byte stream errors. This has nothing to do with the API or samplecode, but with the fact that the used API is deprecated ie. not supported anymore (see below).

Notes: 
- We update MfPack on regular base, so when running in to troubles, please check for updates first.
- I suggest you install MadExcept to see if other issues (like hardware or drivers) are the source of these.
- The MFPlayer API is deprecated: [See here](https://docs.microsoft.com/en-us/windows/win32/api/mfplay/ ) which is also  described in the sourcefile headers.

Thank you, 
Tony.
